-- MySQL Script generated by MySQL Workbench
-- Sun 23 Jun 2019 03:38:05 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`userType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userType` (
  `iduserType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduserType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`iduser`, `type`),
  INDEX `fk_user_userType_idx` (`type` ASC) ,
  CONSTRAINT `fk_user_userType`
    FOREIGN KEY (`type`)
    REFERENCES `mydb`.`userType` (`iduserType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `idcourse` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idcourse`, `iduser`),
  INDEX `fk_course_user1_idx` (`iduser` ASC) ,
  CONSTRAINT `fk_course_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notification` (
  `idnotification` INT NOT NULL,
  `message` VARCHAR(200) NOT NULL,
  `idCourse` INT NOT NULL,
  `seen` BINARY(0) NOT NULL,
  `resource` BLOB NULL,
  PRIMARY KEY (`idnotification`, `idCourse`),
  INDEX `fk_notification_course1_idx` (`idCourse` ASC) ,
  CONSTRAINT `fk_notification_course1`
    FOREIGN KEY (`idCourse`)
    REFERENCES `mydb`.`course` (`idcourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`homework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`homework` (
  `idhomework` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `grade` INT NULL,
  `resource` BLOB NULL,
  `response` BLOB NULL,
  `textResponse` VARCHAR(500) NULL,
  `idcourse` INT NOT NULL,
  PRIMARY KEY (`idhomework`, `idcourse`),
  INDEX `fk_homework_course1_idx` (`idcourse` ASC) ,
  CONSTRAINT `fk_homework_course1`
    FOREIGN KEY (`idcourse`)
    REFERENCES `mydb`.`course` (`idcourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`userHomework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userHomework` (
  `idhomework` INT NOT NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idhomework`, `iduser`),
  INDEX `fk_homework_has_user_user1_idx` (`iduser` ASC) ,
  INDEX `fk_homework_has_user_homework1_idx` (`idhomework` ASC) ,
  CONSTRAINT `fk_homework_has_user_homework1`
    FOREIGN KEY (`idhomework`)
    REFERENCES `mydb`.`homework` (`idhomework`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_homework_has_user_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chat` (
  `iduser` INT NOT NULL,
  `iduser1` INT NOT NULL,
  `message` VARCHAR(150) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`iduser`, `iduser1`),
  INDEX `fk_user_has_user_user2_idx` (`iduser1` ASC) ,
  INDEX `fk_user_has_user_user1_idx` (`iduser` ASC) ,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`iduser1`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
